# Generated by Django 6.0.2 on 2026-02-27 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('manufacturing_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('quantity_manufactured', models.PositiveIntegerField(default=0)),
                ('quantity_sent_to_distributors', models.PositiveIntegerField(default=0)),
                ('batch_status', models.CharField(choices=[('active', 'Active'), ('near_expiry', 'Near Expiry'), ('expired', 'Expired')], default='active', max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('cream', 'Cream'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('other', 'Other')], max_length=20)),
                ('strength', models.CharField(help_text='e.g., 500mg, 250mg/5ml', max_length=100)),
                ('packing_size', models.CharField(help_text='e.g., 10x10, 1x100ml', max_length=100)),
                ('manufacturing_cost_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('trade_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price at which trade buys', max_digits=10)),
                ('retail_price', models.DecimalField(decimal_places=2, default=0.0, help_text='MRP — Maximum Retail Price', max_digits=10)),
                ('distributor_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price charged to distributor', max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crm/products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='crm_products.division')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_location', models.CharField(choices=[('main', 'Main Warehouse'), ('cold_storage', 'Cold Storage'), ('secondary', 'Secondary Warehouse')], default='main', max_length=20)),
                ('low_stock_threshold', models.PositiveIntegerField(default=100, help_text='Alert when available stock falls below this number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_stock', to='crm_products.batchmanagement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_stocks', to='crm_products.productmaster')),
            ],
            options={
                'verbose_name': 'Company Stock',
                'verbose_name_plural': 'Company Stock',
                'ordering': ['product__product_name'],
            },
        ),
        migrations.AddField(
            model_name='batchmanagement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='crm_products.productmaster'),
        ),
    ]
