# Generated by Django 6.0.2 on 2026-06-19 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['name'], 'verbose_name': 'Territory', 'verbose_name_plural': 'Territories'},
        ),
        migrations.AlterField(
            model_name='division',
            name='division_id',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Territory ID'),
        ),
        migrations.AlterField(
            model_name='division',
            name='manager_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Territory Manager'),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Territory Name'),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='crm_products.division', verbose_name='Territory'),
        ),
    ]
