# Generated by Django 6.0.2 on 2026-06-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_products', '0002_alter_division_options_alter_division_division_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaster',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
