# Generated by Django 6.0.2 on 2026-02-27 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_products', '0001_initial'),
        ('crm_sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('doctor_name', models.CharField(max_length=150)),
                ('specialty', models.CharField(max_length=150)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('hospital_name', models.CharField(blank=True, max_length=200, null=True)),
                ('clinic_name', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('estimated_patients_per_day', models.PositiveIntegerField(default=0, help_text='Approximate daily patient footfall')),
                ('estimated_prescription_potential', models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated monthly revenue potential in PKR', max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='crm_sales.area')),
                ('assigned_mrs', models.ManyToManyField(blank=True, related_name='assigned_doctors', to='crm_sales.medicalrepresentative')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['doctor_name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField()),
                ('hospital_clinic_name', models.CharField(blank=True, max_length=200, null=True)),
                ('visit_type', models.CharField(choices=[('new_visit', 'New Visit'), ('follow_up', 'Follow Up'), ('emergency', 'Emergency Visit')], default='follow_up', max_length=15)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_address', models.TextField(blank=True, help_text='Auto-fetched address from coordinates', null=True)),
                ('is_gps_verified', models.BooleanField(default=False, help_text='True when GPS coordinates were captured at time of submission')),
                ('next_follow_up_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='crm_doctors.doctor')),
                ('mr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_visits', to='crm_sales.medicalrepresentative')),
            ],
            options={
                'verbose_name': 'Doctor Visit',
                'verbose_name_plural': 'Doctor Visits',
                'ordering': ['-visit_date', '-visit_time'],
            },
        ),
        migrations.CreateModel(
            name='DoctorInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_type', models.CharField(choices=[('meeting', 'Meeting'), ('sponsorship', 'Sponsorship'), ('gifts', 'Gifts'), ('conference', 'Conference'), ('dinner', 'Dinner / Lunch'), ('samples', 'Samples'), ('other', 'Other')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount in PKR', max_digits=12)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='crm_doctors.doctorvisit')),
            ],
            options={
                'verbose_name': 'Doctor Investment',
                'verbose_name_plural': 'Doctor Investments',
            },
        ),
        migrations.CreateModel(
            name='CompetitorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_product_name', models.CharField(max_length=200)),
                ('competitor_company', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_info', to='crm_doctors.doctorvisit')),
            ],
            options={
                'verbose_name': 'Competitor Info',
                'verbose_name_plural': 'Competitor Info',
            },
        ),
        migrations.CreateModel(
            name='PharmacyReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200)),
                ('store_location', models.CharField(blank=True, max_length=300, null=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_references', to='crm_doctors.doctorvisit')),
            ],
            options={
                'verbose_name': 'Pharmacy Reference',
                'verbose_name_plural': 'Pharmacy References',
            },
        ),
        migrations.CreateModel(
            name='VisitProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('samples_given', models.PositiveIntegerField(default=0)),
                ('promotional_material_given', models.CharField(blank=True, help_text='e.g., Brochures, Pens, Notepad', max_length=200, null=True)),
                ('estimated_units_prescribed_per_day', models.PositiveIntegerField(default=0)),
                ('estimated_units_prescribed_per_month', models.PositiveIntegerField(default=0)),
                ('estimated_value_per_month', models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated monthly prescription value in PKR', max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_product_details', to='crm_products.productmaster')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='crm_doctors.doctorvisit')),
            ],
            options={
                'verbose_name': 'Visit Product Detail',
                'verbose_name_plural': 'Visit Product Details',
            },
        ),
    ]
