# Generated by Django 6.0.2 on 2026-06-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_doctors', '0003_alter_doctorinvestment_investment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorvisit',
            name='visit_type',
            field=models.CharField(choices=[('new_visit', 'Call Done'), ('follow_up', 'Reminder Dropped'), ('emergency', 'Doctor Not Available')], default='follow_up', max_length=15),
        ),
    ]
