# Generated by Django 6.0.2 on 2026-02-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cities_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
