# Generated by Django 6.0.2 on 2026-02-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teams_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
