# Generated by Django 6.0.2 on 2026-02-27 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('area_name', models.CharField(max_length=100)),
                ('area_manager', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'ordering': ['area_name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('region_name', models.CharField(max_length=100)),
                ('regional_manager', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='crm_products.division')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['region_name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mr_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('cnic', models.CharField(help_text='Format: 12345-1234567-1', max_length=15, unique=True, verbose_name='CNIC')),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly salary in PKR', max_digits=10)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='crm/mr_profiles/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('terminated', 'Terminated')], default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrs', to='crm_sales.area')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrs', to='crm_products.division')),
                ('user', models.OneToOneField(blank=True, help_text='Linked login account for MR app access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mr_profile', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrs', to='crm_sales.region')),
            ],
            options={
                'verbose_name': 'Medical Representative',
                'verbose_name_plural': 'Medical Representatives',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='area',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='crm_sales.region'),
        ),
    ]
