# Generated by Django 6.0.2 on 2026-06-19 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_products', '0002_alter_division_options_alter_division_division_id_and_more'),
        ('crm_sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrepresentative',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrs', to='crm_products.division', verbose_name='Territory'),
        ),
        migrations.AlterField(
            model_name='region',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='crm_products.division', verbose_name='Territory'),
        ),
    ]
