# Generated by Django 6.0.2 on 2026-06-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_products', '0003_alter_productmaster_product_name'),
        ('crm_sales', '0002_alter_medicalrepresentative_division_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='division',
        ),
        migrations.AddField(
            model_name='region',
            name='division',
            field=models.ManyToManyField(related_name='regions', to='crm_products.division', verbose_name='Territory'),
        ),
    ]
