# Generated by Django 6.0.2 on 2026-06-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_sales', '0003_remove_region_division_region_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='region',
        ),
        migrations.AddField(
            model_name='area',
            name='region',
            field=models.ManyToManyField(related_name='areas', to='crm_sales.region'),
        ),
    ]
