# Generated by Django 6.0.2 on 2026-02-27 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('distributor_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('ntn_number', models.CharField(blank=True, help_text='National Tax Number', max_length=50, null=True, verbose_name='NTN Number')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=15)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum outstanding credit allowed (PKR)', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Distributor',
                'verbose_name_plural': 'Distributors',
                'ordering': ['distributor_name'],
            },
        ),
        migrations.CreateModel(
            name='DistributorSalesValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_values', to='crm_distributors.distributor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_sales_values', to='crm_products.productmaster')),
            ],
            options={
                'verbose_name': 'Distributor Sales Value',
                'verbose_name_plural': 'Distributor Sales Values',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='DistributorStockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_stock', models.PositiveIntegerField(default=0)),
                ('received_quantity', models.PositiveIntegerField(default=0, help_text='Stock received from company in this period')),
                ('sold_quantity', models.PositiveIntegerField(default=0)),
                ('unsold_quantity', models.PositiveIntegerField(default=0)),
                ('expired_quantity', models.PositiveIntegerField(default=0)),
                ('near_expiry_quantity', models.PositiveIntegerField(default=0)),
                ('report_period_start', models.DateField()),
                ('report_period_end', models.DateField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributor_stock_entries', to='crm_products.batchmanagement')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='crm_distributors.distributor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_stock_entries', to='crm_products.productmaster')),
            ],
            options={
                'verbose_name': 'Distributor Stock Entry',
                'verbose_name_plural': 'Distributor Stock Entries',
                'ordering': ['-date_submitted'],
            },
        ),
    ]
