# Generated by Django 6.0.2 on 2026-02-27 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_distributors', '0001_initial'),
        ('crm_doctors', '0001_initial'),
        ('crm_products', '0001_initial'),
        ('crm_sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('store_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('drug_license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_stores', to='crm_sales.area')),
                ('distributor', models.ForeignKey(blank=True, help_text='Primary distributor supplying this store', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_stores', to='crm_distributors.distributor')),
                ('linked_doctors', models.ManyToManyField(blank=True, help_text='Doctors who refer patients to this store', related_name='linked_stores', to='crm_doctors.doctor')),
            ],
            options={
                'verbose_name': 'Medical Store',
                'verbose_name_plural': 'Medical Stores',
                'ordering': ['store_name'],
            },
        ),
        migrations.CreateModel(
            name='StoreProductTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out of Stock'), ('low_stock', 'Low Stock')], default='available', max_length=15)),
                ('monthly_sales_estimate', models.PositiveIntegerField(default=0, help_text='Estimated units sold per month at this store')),
                ('monthly_revenue_estimate', models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated monthly revenue in PKR', max_digits=12)),
                ('last_updated_by_mr', models.CharField(blank=True, help_text='MR name who last updated this record', max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_trackings', to='crm_products.productmaster')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_trackings', to='crm_stores.medicalstore')),
            ],
            options={
                'verbose_name': 'Store Product Tracking',
                'verbose_name_plural': 'Store Product Trackings',
                'ordering': ['store__store_name', 'product__product_name'],
                'unique_together': {('store', 'product')},
            },
        ),
    ]
