# Generated by Django 6.0.2 on 2026-02-27 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_distributors', '0001_initial'),
        ('crm_doctors', '0001_initial'),
        ('crm_products', '0001_initial'),
        ('crm_sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('6_months', '6 Months Warning'), ('3_months', '3 Months Warning'), ('1_month', '1 Month Warning'), ('expired', 'Expired')], max_length=15)),
                ('source', models.CharField(choices=[('company_stock', 'Company Stock'), ('distributor_stock', 'Distributor Stock'), ('batch', 'Batch')], max_length=20)),
                ('batch_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('quantity_at_risk', models.PositiveIntegerField(default=0)),
                ('recipient', models.CharField(choices=[('admin', 'Admin'), ('sales_manager', 'Sales Manager'), ('distributor', 'Distributor')], max_length=20)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, max_length=150, null=True)),
                ('alert_sent_at', models.DateTimeField(auto_now_add=True)),
                ('distributor', models.ForeignKey(blank=True, help_text='Populated when source is distributor_stock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expiry_alerts', to='crm_distributors.distributor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_alerts', to='crm_products.productmaster')),
            ],
            options={
                'verbose_name': 'Expiry Alert',
                'verbose_name_plural': 'Expiry Alerts',
                'ordering': ['-alert_sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_month', models.DateField()),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('growth_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Month-over-month growth %', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_snapshots', to='crm_distributors.distributor')),
                ('mr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_snapshots', to='crm_sales.medicalrepresentative')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='crm_products.productmaster')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_snapshots', to='crm_sales.region')),
            ],
            options={
                'verbose_name': 'Product Performance Snapshot',
                'verbose_name_plural': 'Product Performance Snapshots',
                'ordering': ['-snapshot_month', 'product__product_name'],
            },
        ),
        migrations.CreateModel(
            name='DistributorPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_month', models.DateField()),
                ('total_sales_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_units_sold', models.PositiveIntegerField(default=0)),
                ('total_unsold_stock', models.PositiveIntegerField(default=0)),
                ('total_expired_stock', models.PositiveIntegerField(default=0)),
                ('efficiency_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='% of received stock that was sold (not expired or unsold)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='crm_distributors.distributor')),
            ],
            options={
                'verbose_name': 'Distributor Performance Snapshot',
                'verbose_name_plural': 'Distributor Performance Snapshots',
                'ordering': ['-snapshot_month'],
                'unique_together': {('distributor', 'snapshot_month')},
            },
        ),
        migrations.CreateModel(
            name='DoctorPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_month', models.DateField()),
                ('estimated_prescription_per_month', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_investment_given', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_visits_received', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='crm_doctors.doctor')),
            ],
            options={
                'verbose_name': 'Doctor Performance Snapshot',
                'verbose_name_plural': 'Doctor Performance Snapshots',
                'ordering': ['-snapshot_month'],
                'unique_together': {('doctor', 'snapshot_month')},
            },
        ),
        migrations.CreateModel(
            name='MRPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_month', models.DateField(help_text='Set to the 1st of the month being summarized')),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('gps_verified_visits', models.PositiveIntegerField(default=0)),
                ('total_doctors_covered', models.PositiveIntegerField(default=0)),
                ('unique_doctors_visited', models.PositiveIntegerField(default=0)),
                ('total_prescription_value_generated', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of estimated prescription values from all visits', max_digits=15)),
                ('total_investment_given', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('gps_verified_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='% of visits with GPS verification', max_digits=5)),
                ('working_efficiency_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Composite score (0–100)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='crm_sales.medicalrepresentative')),
            ],
            options={
                'verbose_name': 'MR Performance Snapshot',
                'verbose_name_plural': 'MR Performance Snapshots',
                'ordering': ['-snapshot_month', 'mr__name'],
                'unique_together': {('mr', 'snapshot_month')},
            },
        ),
    ]
