# Generated by Django 6.0.2 on 2026-02-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='key_benefits',
            field=models.TextField(blank=True, help_text='Key benefits or features of the product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_size',
            field=models.CharField(blank=True, help_text='Pack size or quantity (e.g., 30 tablets, 100ml)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, help_text='Optional product video (e.g., usage demonstration)', null=True, upload_to='products/videos/'),
        ),
    ]
