# Generated by Django 6.0.2 on 2026-02-22 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_key_benefits_product_pack_size_product_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
